name: Build PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Clear TypeScript build info
        run: |
          echo "TypeScript 빌드 캐시 삭제"
          rm -rf node_modules/.tmp
          rm -rf node_modules/.cache

      - name: Check TypeScript compilation
        run: pnpm tsc -b

      - name: Build project
        run: pnpm run build
